spring:
 cloud:
  gateway:
   routes[0]:
    id: DEPARTMENTSERVICE
    uri: lb://DEPARTMENTSERVICE
    predicates[0]:
     path: /dept/**
    
server:
 port: 8083
eureka:
 client:
  service-url:
   defaultZone: http://localhost:8761/eureka
management:
 tracing:
  sampling:
   probability: 0.1

 
